global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'todo-app'
    static_configs:
      - targets: ['todo-app:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'alloy'
    static_configs:
      - targets: ['alloy:12345']
    metrics_path: '/metrics'

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
